### ISSUE TITLE
Error: failed to get info about account DqgmWxe2PPrfy45Ja3UPyFGwcbRzkRuwXt3NyxjX8krg: FetchError: request to https://api.mainnet-beta.solana.com/ failed, reason: connect ETIMEDOUT 108.160.163.112:443

### ISSUE THREAD

**Issue by 0xbe1** [Bonfida/solana-name-service-guide#3]
My code (modified from https://github.com/Bonfida/solana-name-service-guide#reverse-look-up):

```js
const {performReverseLookup} = require("@bonfida/spl-name-service")
const {clusterApiUrl, Connection, PublicKey} = require("@solana/web3.js")

// Public key of bonfida.sol
const domainKey = new PublicKey("Crf8hzfthWGbGbLTVCiqRqV5MVnbpHB1L9KQMd6gsinb");
const connection = new Connection(clusterApiUrl('mainnet-beta'));
performReverseLookup(connection, domainKey).then(data => console.log(data));
```

What I get:

```
$ node sol.js
/Users/0xbe1/source/0xbe1/ns3/node_modules/@solana/web3.js/lib/index.cjs.js:5508
      throw new Error('failed to get info about account ' + publicKey.toBase58() + ': ' + e);
            ^

Error: failed to get info about account DqgmWxe2PPrfy45Ja3UPyFGwcbRzkRuwXt3NyxjX8krg: FetchError: request to https://api.mainnet-beta.solana.com/ failed, reason: connect ETIMEDOUT 108.160.163.112:443
    at Connection.getAccountInfo (/Users/0xbe1/source/0xbe1/ns3/node_modules/@solana/web3.js/lib/index.cjs.js:5508:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.retrieve (/Users/0xbe1/source/0xbe1/ns3/node_modules/@bonfida/spl-name-service/dist/state.js:14:27)
    at async performReverseLookup (/Users/0xbe1/source/0xbe1/ns3/node_modules/@bonfida/spl-name-service/dist/utils.js:131:16)
```

Any help? Thanks!

**Comment by dr497** [comment]
When I run the code you posted I get the expected outcome

```
$ tsc && node dist/dev.js
bonfida
```

Looking at the error message `FetchError: request to https://api.mainnet-beta.solana.com/ failed, reason: connect ETIMEDOUT 108.160.163.112:443` it looks like it's a connection issue. Might have been a temporary issue between your machine and the default RPC node.

Could you try with another RPC endpoint?

**Comment by 0xbe1** [comment]
@dr497 thanks for helping, I confirm it is an issue with my local network.
