### ISSUE TITLE
Error: Invalid name account provided

### ISSUE THREAD

**Issue by 0xbe1** [Bonfida/solana-name-service-guide#4]
I have a program below following the [guide](https://github.com/Bonfida/solana-name-service-guide#resolve-a-domain-name).

```ts
import {
  getHashedName,
  getNameAccountKey,
  NameRegistryState,
} from '@bonfida/spl-name-service'
import { clusterApiUrl, Connection, PublicKey } from '@solana/web3.js'

const SOL_TLD_AUTHORITY = new PublicKey(
  '58PwtjSDuFHuUkYjH9BYnnQKHfwo9reZhC2zMJv9JPkx'
)

const username = "random"
const solName = `${username}.sol`
try {
  const connection = new Connection(clusterApiUrl('mainnet-beta'))
  const hashedName = await getHashedName(username)
  const domainKey = await getNameAccountKey(
    hashedName,
    undefined,
    SOL_TLD_AUTHORITY
  )
  const { registry, nftOwner } = await NameRegistryState.retrieve(connection, domainKey)
  if (registry.owner !== null) {
    console.log({
      data: {
        exist: true,
        displayname: solName,
        href: `https://explorer.solana.com/address/${registry.owner.toBase58()}`,
      },
    })
  } else {
    console.log({ data: { exist: false, displayname: solName } })
  }
} catch (error) {
  console.log('Error: ', error)
}
```

Turns out the code never reaches the happy path, instead it prints the error log below.

```
Error:  Error: Invalid name account provided
    at Function.retrieve (/var/task/node_modules/@bonfida/spl-name-service/dist/state.js:17:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async handler (/var/task/.next/server/pages/api/solana.js:35:42)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:182:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:386:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:488:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:228:32)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:600:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:307:20)
    at async Server.<anonymous> (/var/task/___next_launcher.js:32:9)
```

Any help? Thanks! @dr497

**Comment by dr497** [comment]
Running the code on my end with node I get the following output

```
{
  data: {
    exist: true,
    displayname: 'random.sol',
    href: 'https://explorer.solana.com/address/85mzQzu2DZ1yzbTm9d3F9wUenoFyn2HqdD1mviK2UKPZ'
  }
}
```

Looking at your logs it seems you are running this on a NextJS server? Can you try with node and see if you still have the issue?

**Comment by 0xbe1** [comment]
@dr497 Thanks for the quick reply!

Yes, I was running the code on [vercel function](https://vercel.com/docs/concepts/functions/introduction).

I tried to run this with local `node` but as in #3, I run into the timeout issue again, probably because my local network is not quite working :( but given you are able to produce the expected result, I believe it has to do with nextjs, and I will ask their community.

BTW, what node version are you running locally?

**Comment by dr497** [comment]
I am not familiar with Vercel functions but it might be the issue. I am locally running `v16.6.0`

**Comment by 0xbe1** [comment]
@dr497 Hi, is there any chance you can try the script with node 14, so that we know if it is a vercel problem or a node version problem? Since vercel runs node version 14.

I tried, but I am faced with a network issue, both node 14 and node 16 produce the same result on my end.

```
(base) ➜  name3 git:(main) ✗ node solana.js
Error:  Error: failed to get info about account GCYxPhZT8pyUZmryem9V5rtbGzqAkrf512oTLmvTWh8Q: FetchError: request to https://api.mainnet-beta.solana.com/ failed, reason: connect ETIMEDOUT 69.197.153.180:443
    at Connection.getAccountInfo (/Users/0xbe1/source/0xbe1/name3/node_modules/@solana/web3.js/lib/index.cjs.js:5508:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.retrieve (/Users/0xbe1/source/0xbe1/name3/node_modules/@bonfida/spl-name-service/dist/state.js:15:29)
    at async main (/Users/0xbe1/source/0xbe1/name3/solana.js:23:34)
(base) ➜  name3 git:(main) ✗ fnm use 14
Using Node v14.19.1
(base) ➜  name3 git:(main) ✗ node solana.js
Error:  Error: failed to get info about account GCYxPhZT8pyUZmryem9V5rtbGzqAkrf512oTLmvTWh8Q: FetchError: request to https://api.mainnet-beta.solana.com/ failed, reason: connect ETIMEDOUT 108.160.166.42:443
    at Connection.getAccountInfo (/Users/0xbe1/source/0xbe1/name3/node_modules/@solana/web3.js/lib/index.cjs.js:5508:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Function.retrieve (/Users/0xbe1/source/0xbe1/name3/node_modules/@bonfida/spl-name-service/dist/state.js:15:29)
    at async main (/Users/0xbe1/source/0xbe1/name3/solana.js:23:34)
```

Appreciate it :)

**Comment by dr497** [comment]
So I tried with v14.19.1 and here is the output

```
% nvm version
v14.19.1
% yarn dev
yarn run v1.22.18
$ tsc && node dist/test.js
{
  data: {
    exist: true,
    displayname: 'random.sol',
    href: 'https://explorer.solana.com/address/85mzQzu2DZ1yzbTm9d3F9wUenoFyn2HqdD1mviK2UKPZ'
  }
}
✨  Done in 6.93s.
```

Maybe `https://api.mainnet-beta.solana.com/` is blocking IPs from data centres? Have you tried `https://solana-api.projectserum.com` for instance?

**Comment by 0xbe1** [comment]
@dr497 is there a way to specify the domain name it queries against?

**Comment by dr497** [comment]
Yes, you can specify the RPC endpoint you want in the `Connection` constructor:

```js
const connection = new Connection("https://solana-api.projectserum.com")
```

**Comment by 0xbe1** [comment]
@dr497 projectserum solana api works for me on my local dev env, but it still produces the same error on Vercel. I am further following up with them at https://github.com/vercel/community/discussions/507

Thank you for your help.

**Comment by dr497** [comment]
@0xbe1 Please keep me posted about how things go and if you find the solution post it here, I am sure this will help people in the future 🙏

**Comment by 0xbe1** [comment]
@dr497 It turns out:

"Invalid name account provided" is the error message when a name is untaken. What I need to do is simply handle this error by checking `error.message === "Invalid name account provided"`

Thank you for your help!
